// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package database

import (
	"context"
	"database/sql"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (title, description, link, last_updated)
VALUES (?, ?, ?, ?)
`

type CreateChannelParams struct {
	Title       string
	Description sql.NullString
	Link        string
	LastUpdated sql.NullTime
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.ExecContext(ctx, createChannel,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.LastUpdated,
	)
	return err
}
