// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Channel struct {
	ID          int64
	Title       string
	Description sql.NullString
	Link        string
	LastUpdated sql.NullTime
	CreatedAt   sql.NullTime
}
